all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/ansible_id_rsa
    ansible_ssh_common_args: >
      -o StrictHostKeyChecking=no

  children:

    #################################################
    # 외부망 (Direct Access)
    #################################################
    web:
      hosts:
        nginx1:
          ansible_host: 172.16.6.51
        nginx2:
          ansible_host: 172.16.6.52

    was:
      hosts:
        was1:
          ansible_host: 172.16.6.53
        was2:
          ansible_host: 172.16.6.54

    ops:
      hosts:
        monitoring:
          ansible_host: 172.16.6.57
        dr1:
          ansible_host: 172.16.6.58
        df2:
          ansible_host: 172.16.6.59

    #################################################
    # 내부망 (via Keepalived VIP Gateway)
    #################################################
    internal:
      vars:
        ansible_ssh_common_args: >
          -o ProxyJump=ansible@10.1.1.1
          -o StrictHostKeyChecking=no
      children:
        internal_common:
          hosts:
            redis:
              ansible_host: 10.1.1.10
            ai_worker:
              ansible_host: 10.1.1.20
            DB_VIP:
              ansible_host: 10.1.1.40
        db_lb:
          hosts:
            DB_LB_01:
              ansible_host: 10.1.1.41
            DB_LB_02:
              ansible_host: 10.1.1.42
        db:
          hosts:
            DB_01:
              ansible_host: 10.1.5.10
            DB_02:
              ansible_host: 10.1.5.20
            DB_03:
              ansible_host: 10.1.5.30
