all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/ansible_id_rsa

  children:

    #################################################
    # 외부망 (Direct Access)
    #################################################
    web:
      hosts:
        nginx1:
          ansible_host: 172.16.6.51
        nginx2:
          ansible_host: 172.16.6.52

    was:
      hosts:
        was1:
          ansible_host: 172.16.6.53
        was2:
          ansible_host: 172.16.6.54

    ops:
      hosts:
        monitoring:
          ansible_host: 172.16.6.57
        dr_ha:
          ansible_host: 172.16.6.58
        dr_repo:
          ansible_host: 172.16.6.59

    #################################################
    # 내부 서비스망 (10.1.1.x)
    # → ssh config에서 ProxyJump=bastion 적용
    #################################################
    internal:
      children:
        internal_common:
          hosts:
            redis1:
              ansible_host: 10.1.1.5
            redis2:
              ansible_host: 10.1.1.10
            ai_worker:
              ansible_host: 10.1.1.20
        vs:
          hosts:
            video_storage:
              ansible_host: 10.1.1.50

        pgsql_vip:
          hosts:
            db_vip:
              ansible_host: 10.1.1.40

        pgsql_lb:
          hosts:
            db_lb_01:
              ansible_host: 10.1.1.41
            db_lb_02:
              ansible_host: 10.1.1.42

    #################################################
    # DB 전용망 (10.1.5.x)
    # → Ansible 서버 NIC 직결 (ProxyJump ❌)
    #################################################
    pgsql_db:
      hosts:
        dba:
          ansible_host: 10.1.5.10
        dbs:
          ansible_host: 10.1.5.20
        dbb:
          ansible_host: 10.1.5.30
