all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/ansible_id_rsa
    ansible_ssh_common_args: >
      -o StrictHostKeyChecking=no

  children:

    #################################################
    # 외부망 (Direct Access)
    #################################################
    web:
      hosts:
        nginx1:
          ansible_host: 172.16.6.51
        nginx2:
          ansible_host: 172.16.6.52

    was:
      hosts:
        was1:
          ansible_host: 172.16.6.53
        was2:
          ansible_host: 172.16.6.54

    ops:
      hosts:
        monitoring:
          ansible_host: 172.16.6.59
        dr:
          ansible_host: 172.16.6.60

    #################################################
    # 내부망 (via Keepalived VIP Gateway)
    #################################################
    internal:
      vars:
        ansible_ssh_common_args: >
          -o ProxyJump=ansible@10.1.1.1
          -o StrictHostKeyChecking=no
      children:
        internal_common:
          hosts:
            redis:
              ansible_host: 10.1.1.90
            ai_worker:
              ansible_host: 10.1.1.20
        storage:
          hosts:
            DB_LB01:
              ansible_host: 10.1.1.41
            DB_LB02:
              ansible_host: 10.1.1.42
